"""Initial migration

Revision ID: 8c7c98321bc5
Revises: 
Create Date: 2020-10-01 17:32:33.788570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy.sql import table

# revision identifiers, used by Alembic.
revision = '8c7c98321bc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    Users = table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True)
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    # ### end Alembic commands ###

    user = {
            'email':'admin@xytovet.com',
            'password_hash': 'pbkdf2:sha256:150000$u0MxI5k3$e703c3b3c58e473ca6c6b5787df2073022558dcfeb699868d157ee1e1a078967',
            'admin': True,
            'client_id': True,
            'notifications': False
    }
    op.bulk_insert(Users,[user])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
