"""empty message

Revision ID: fc999df119ab
Revises: 8c7c98321bc5
Create Date: 2020-10-16 15:51:54.616559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc999df119ab'
down_revision = '8c7c98321bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_sent', sa.Integer(), server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('notifications_sent')

    # ### end Alembic commands ###
